"""Stage 23: assemble evidence-based findings and bounded recommendations."""

import pandas as pd

from utils.data_loader import read_json, write_json, write_text
from utils.runner import stage_cli


def run(ctx):
    """Separate observed facts, associations, predictions, and proposed actions."""
    answers = read_json(ctx.path("reports", "business_insights", "sql_answers.json"))
    stats = read_json(ctx.path("reports", "statistical", "statistics.json"))
    model = read_json(ctx.path("models", "evaluation", "holdout_metrics.json"))
    cleaning = read_json(ctx.path("reports", "data_quality", "cleaning_log.json"))
    selected = model["metrics"]["selected"]
    baseline = model["metrics"]["seasonal_naive"]
    findings = []
    for answer in answers:
        findings.append(
            {
                "type": "Observed descriptive fact",
                "question": answer["question"],
                "evidence": answer["output"],
                "numerical_result": answer["preview"],
                "interpretation": answer["interpretation"],
                "recommended_action": answer["potential_action"],
            }
        )
    findings.extend(
        [
            {
                "type": "Statistical association",
                "question": "Do customer-level basket values differ geographically?",
                "evidence": "reports/statistical/statistics.json",
                "numerical_result": {
                    "difference_gbp": stats["mean_difference_gbp"],
                    "ci95": stats["mean_difference_ci95_gbp"],
                },
                "interpretation": "Customer-level observational contrast excludes anonymous and multi-country buyers.",
                "recommended_action": "Investigate customer mix; do not infer a causal geographic effect.",
            },
            {
                "type": "Evaluated prediction",
                "question": "Can next-day recorded sales be predicted usefully?",
                "evidence": "models/evaluation/holdout_metrics.json",
                "numerical_result": {
                    "model": model["selected_model"],
                    "holdout": selected,
                    "seasonal_baseline": baseline,
                },
                "interpretation": f"Holdout MAE difference versus seasonal baseline is "
                f"GBP {selected['MAE'] - baseline['MAE']:,.2f} (lower is better).",
                "recommended_action": (
                    "Run a contemporary shadow evaluation before operational use."
                    if selected["MAE"] < baseline["MAE"]
                    else "Retain the seasonal baseline; investigate richer data before operational use."
                ),
            },
            {
                "type": "Observed data-quality fact",
                "question": "How many records remain analytically usable?",
                "evidence": "reports/data_quality/cleaning_log.json",
                "numerical_result": cleaning,
                "interpretation": f"{cleaning['accepted_rows']:,} accepted rows plus "
                f"{cleaning['quarantined_rows']:,} quarantined rows reconcile to source.",
                "recommended_action": "Review quarantine reasons and resolve source identity ambiguity.",
            },
        ]
    )
    markdown = (
        "# Business insights\n\n"
        "This report distinguishes measured history from statistical associations and forecasts. "
        "Recommended actions require business validation; the dataset reflects a historical retailer.\n\n"
    )
    for finding in findings:
        markdown += (
            f"## {finding['question']}\n\n"
            f"**Type:** {finding['type']}\n\n"
            f"**Evidence:** [{finding['evidence']}](../../{finding['evidence']})\n\n"
            f"**Numerical result:** `{finding['numerical_result']}`\n\n"
            f"**Interpretation:** {finding['interpretation']}\n\n"
            f"**Recommended action:** {finding['recommended_action']}\n\n"
        )
    overview = (
        "# Computed project findings\n\n"
        f"Source rows: {cleaning['original_rows']:,}; accepted: {cleaning['accepted_rows']:,}; "
        f"quarantined: {cleaning['quarantined_rows']:,}.\n\n"
        f"Selected model: **{model['selected_model']}**. "
        f"Test period: {model['holdout_start']} to {model['holdout_end']}.\n\n"
        + pd.DataFrame(model["metrics"]).T.to_markdown()
        + "\n\nSee [business insights](../reports/business_insights/insights.md) for observations, "
        "evidence, and recommendations. Metrics are regenerated by the pipeline."
    )
    return [
        write_json(findings, ctx.path("reports", "business_insights", "insights.json")),
        write_text(markdown, ctx.path("reports", "business_insights", "insights.md")),
        write_text(overview, ctx.root / "docs/project_findings.md"),
    ]


if __name__ == "__main__":
    stage_cli(23)
